default: &default
  adapter: postgresql
  encoding: unicode
  prepared_statements: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: access_pdf_development

test:
  <<: *default
  host: localhost
  database: access_pdf_test

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  port: 5432
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  connect_timeout: 5
  checkout_timeout: 10
  variables:
    statement_timeout: 10000 # 10 seconds
