name: Python Component Linting and Tests

on:
  pull_request:
    branches: [ main, dev ]

permissions:
  contents: read

env:
  LINTING_BUDGET: 3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./python_components/ci/requirements.txt ]; then pip install -r ./python_components/ci/requirements.txt; fi
        pip install python_components/evaluation
        pip install python_components/document_inference
        python -m spacy download en_core_web_sm
    - name: Run Linting
      run: |
        ./python_components/ci/scripts/ci_run_linting.sh "./python_components/."
    - name: Run Tests
      run: |
        pytest python_components/ -W ignore::DeprecationWarning